rds-development: 
  provider: AWS
  service: RDS
  credentials: 
    aws_access_key_id: XXXXXXXXXXXXXXXXXXXX
    aws_secret_access_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  delay: 120
  exclude_resources: 
  - parameters
  - security_groups
  - parameter_groups
  - snapshots

rds-production: 
  provider: AWS
  service: RDS
  credentials: 
    aws_access_key_id: XXXXXXXXXXXXXXXXXXXX
    aws_secret_access_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  delay: 120
  exclude_resources: 
  - parameters
  - security_groups
  - parameter_groups
  - snapshots
