# REQUIRED - The S3 bucket name where all backups will be saved
backup_bucket: rdsbackups

# Backups can be prefixed with backup_prefix if desired.
# (Do not include a leading or trailing /)
# default value = nil

#backup_prefix: testing

# The rds_security_group must be defined in each
# RDS account, and be open to this server, so that the
# mysqldump utlility can connect.
# default value = rds-backup-service

#rds_security_group: rds-backup-service

# The ec2_security_group must be defined in the EC2 account
# under which this service runs.
# default value = rds-backup-service

#ec2_security_group: rds-backup-service

# Where to store DB data while compressing it, before upload
# defaults to Ruby's Dir.tmpdir

#tmp_dir: "/tmp"
