# The S3 bucket name where all backups will be saved
backup_bucket: rdsbackups

# All backups will be prefixed with backup_prefix 
# (no leading or trailing / necessary)
backup_prefix: testing

# The rds_security_group must be defined in each
# RDS account, and be open to this server, so that the
# mysqldump can take place!
rds_security_group: rds-backup-service

# Where to store DB data while compressing it, before upload
# defaults to Ruby's Dir.tmpdir
#tmp_dir: "/tmp"
